services:
  stress-o-matic:
    build:
      context: ..
      dockerfile: docker_images/Dockerfile-ubuntu
    ports:
      - "8080:8080"
    volumes:
      - ../logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 20G
          cpus: 1
    env_file:
      - ../.env
